### PR TITLE
Iyovcheva/externalised config in catalog definition aled

### PR DESCRIPTION
**Pull request by aledsage**

### CODE REVIEW

**Comment by ivanayov** [comment]
Good improvement to test all catalog elements.

I'm not sure if we need to avoid parsing "items", because they are already parsed in `BasicBrooklynCatalog.collectCatalogItems(yaml)`, but it's still optimized that way, so looks good.

**Comment by aledsage** [comment]
I had to guard against the spec-parsing not being there for this test:
- `CatalogScanTest.testAnnotationIsDefault:171->doTestAnnotationIsDefault:187 expected [2] but found [0]`

When it was parsing items, I saw failures for:
- `EntitiesYamlTest.testScopeReferences:503->AbstractYamlTest.addCatalogItems:142->AbstractYamlTest.addCatalogItems:146 » IllegalArgument`
- `SpecParameterUnwrappingTest.testParametersCoercedOnSetAndReferences:304->AbstractYamlTest.addCatalogItems:142->AbstractYamlTest.addCatalogItems:146 » IllegalArgument`

Not sure why it didn't flag any problems in the PR though - it is supposed to run apache jenkins against any new PR.

**Comment by aledsage** [comment]
For `BasicBrooklynCatalog.collectCatalogItems(yaml)` having already parsed the items, I mean a different kind parsing. The `collectCatalogItems(yaml)` just parses the YAML into lists, maps, etc. The failure happens if it converts the external-config within an item into deferred-suppliers, and then tries to do a deepResolve of the tasks. The things inside the item cannot be resolved yet, because the blueprint is not instantiated/executed.

**Comment by ivanayov** [comment]
Thanks for the failures info! Looks good to merge

**Comment by aledsage** [comment]
@iyovcheva you'll have to be the one to merge this, given it is a PR against your own repo. You should be able to click the merge button if you want to merge it into your branch. That will automatically update https://github.com/apache/incubator-brooklyn/pull/1130

**Pull request merged**
